### ISSUE TITLE
`NameError: name 'wr' is not defined` in chapter03/01-prep_data.ipynb

### ISSUE THREAD

**Issue by tkbky** [PacktPublishing/Getting-Started-with-Amazon-SageMaker-Studio#1]
Hi @michaelhsieh42 ,

First of all, thank you for the amazing content in this book (😄 I'm just a few chapters in, but feels pretty good so far)

I've only begun to try a few examples from this book, and I've run into an error `NameError: name 'wr' is not defined` with chapter 3. Can you take a look?

**Comment by michaelhsieh42** [comment]
Thanks for reporting this issue. I have addressed it in the notebook.
